# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('phone_number', models.CharField(blank=True, max_length=9)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('email_validated', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campsite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_locality', models.CharField(max_length=50)),
                ('field_address', models.CharField(max_length=50)),
                ('field_postal_code', models.CharField(max_length=6)),
                ('field_phone_number', models.CharField(blank=True, max_length=9)),
                ('field_email', models.CharField(blank=True, max_length=100)),
                ('field_website', models.CharField(blank=True, max_length=200)),
                ('ratings_number', models.IntegerField(null=True)),
                ('average_rating', models.FloatField(null=True)),
                ('field_photo', models.ImageField(null=True, upload_to='')),
                ('field_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Convenience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('canteen', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('easy_access', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('equipment_rental', models.BooleanField(default=False)),
                ('campsite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testApp.Campsite')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_NIP', models.CharField(max_length=10)),
                ('company_REGON', models.CharField(max_length=9)),
                ('company_locality', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=50)),
                ('company_postal_code', models.CharField(max_length=5)),
                ('account_validated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place_type', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('dimension', models.FloatField()),
                ('number_of_places', models.IntegerField()),
                ('limit_of_places', models.IntegerField(null=True)),
                ('campsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.Campsite')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('campsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.Campsite')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('hour_of_reservation', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.Customer')),
                ('fieldOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.FieldOwner')),
            ],
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='reservation',
            field=models.ManyToManyField(to='testApp.Reservation'),
        ),
        migrations.AddField(
            model_name='campsite',
            name='customers',
            field=models.ManyToManyField(through='testApp.Rating', to='testApp.Customer'),
        ),
        migrations.AddField(
            model_name='campsite',
            name='field_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.FieldOwner'),
        ),
    ]
